const lessons=[
{id:1,title:'مقدمه‌ای بر اندروید و جت‌پک کامپوز',desc:'از شناخت سیستم‌عامل اندروید تا ساخت اولین پروژه با Kotlin و Jetpack Compose؛ این درس پایه‌های مسیر توسعه اندروید را می‌سازد.',topics:['اندروید چیست؟','روش‌های توسعه موبایل','Android Studio','Android SDK','Emulator','Kotlin','Jetpack Compose','ساختار پروژه','اولین پروژه'],sections:[
['اندروید چیست؟',['اندروید یک سیستم‌عامل مبتنی بر Linux و یک پلتفرم نرم‌افزاری برای دستگاه‌های موبایل، تلویزیون، خودرو و دیگر دستگاه‌های هوشمند است.','برنامه‌های اندرویدی معمولاً با Kotlin یا Java نوشته می‌شوند و برای ساخت رابط کاربری مدرن، Jetpack Compose یکی از ابزارهای اصلی است.','هر برنامه اندرویدی می‌تواند چند صفحه و بخش داشته باشد و سیستم‌عامل مدیریت چرخه حیات، مجوزها، منابع و اجرای آن را بر عهده دارد.']],
['روش‌های توسعه برنامه‌های موبایل',['توسعه Native برای هر سیستم‌عامل با ابزارها و زبان‌های مخصوص همان سیستم انجام می‌شود.','توسعه Cross-platform امکان ساخت برنامه برای چند سیستم‌عامل با یک کدبیس را فراهم می‌کند.','برای یادگیری عمیق توسعه اندروید، آشنایی با ابزارهای Native اندروید و Kotlin بسیار مهم است.']],
['ابزارهای توسعه اندروید',['Android Studio محیط توسعه رسمی اندروید است و امکاناتی مانند ویرایشگر کد، مدیریت پروژه، ابزارهای طراحی، شبیه‌ساز و Debugger را در اختیار توسعه‌دهنده قرار می‌دهد.','Android SDK مجموعه‌ای از APIها، ابزارها و کتابخانه‌هایی است که برای ساخت، تست و اجرای برنامه‌های اندرویدی استفاده می‌شود.','Android Emulator یک دستگاه اندرویدی مجازی روی رایانه است که برای اجرای آزمایشی برنامه بدون گوشی واقعی استفاده می‌شود.']],
['Android Studio',['در Android Studio پروژه را ایجاد و مدیریت می‌کنیم، کد Kotlin می‌نویسیم، خطاها را بررسی می‌کنیم و برنامه را روی Emulator یا دستگاه واقعی اجرا می‌کنیم.','بخش Project فایل‌ها و پوشه‌های پروژه را نشان می‌دهد؛ Editor برای نوشتن کد است و Logcat برای مشاهده پیام‌های اجرایی و خطاها کاربرد دارد.','ابزار Gradle فرایند Build پروژه و مدیریت وابستگی‌ها را کنترل می‌کند.']],
['Kotlin',['Kotlin یک زبان مدرن، خوانا و ایمن است که زبان اصلی پیشنهادی برای توسعه جدید اندروید محسوب می‌شود.','ویژگی‌هایی مانند Null Safety، توابع کوتاه، Data Class و Lambda باعث می‌شوند کد Kotlin برای پروژه‌های اندرویدی مناسب باشد.']],
['Jetpack Compose چیست؟',['Jetpack Compose یک ابزار مدرن و Declarative برای ساخت رابط کاربری اندروید است.','در Compose به جای تعریف دستی بسیاری از Viewها، رابط کاربری را با توابع Composable و بر اساس وضعیت برنامه توصیف می‌کنیم.','با Compose می‌توان UI را سریع‌تر توسعه داد و Preview آن را در محیط Android Studio مشاهده کرد.']],
['ساختار پروژه اندروید',['پوشه app معمولاً شامل کد و منابع اصلی برنامه است.','فایل‌های Gradle برای تنظیم Build و وابستگی‌ها استفاده می‌شوند.','پوشه res برای منابعی مانند تصاویر، آیکون‌ها و بعضی منابع رابط کاربری است.','AndroidManifest.xml اطلاعات مهم برنامه مانند Activityها، مجوزها و ویژگی‌های برنامه را تعریف می‌کند.']],
['ساخت اولین پروژه Compose',['Android Studio را باز کنید و New Project را انتخاب کنید.','یک الگوی مناسب مانند Empty Activity را انتخاب کنید.','زبان پروژه را Kotlin انتخاب کنید و تنظیمات نام و محل پروژه را مشخص کنید.','پس از ایجاد پروژه، اجازه دهید Gradle وابستگی‌ها را آماده کند و سپس برنامه را با Run اجرا کنید.','برای آزمایش می‌توانید یک Emulator بسازید یا گوشی واقعی را به‌عنوان دستگاه تست انتخاب کنید.']],
['نمونه کد اولین Compose',[]],
['خلاصه درس',['بعد از این درس باید بدانید اندروید چیست و توسعه Native چه تفاوتی با روش‌های دیگر دارد.','باید نقش Android Studio، Android SDK و Emulator را بشناسید.','باید بدانید Kotlin و Jetpack Compose چه هستند و چرا در توسعه مدرن اندروید استفاده می‌شوند.','باید بتوانید ساختار کلی یک پروژه را تشخیص دهید و یک پروژه ساده Compose ایجاد و اجرا کنید.']],
['تمرین‌ها',['Android Studio را نصب و اجرا کنید.','یک پروژه Kotlin با Empty Activity بسازید.','متن پیش‌فرض صفحه را تغییر دهید.','نام برنامه را تغییر دهید.','یک آیکون مناسب برای برنامه انتخاب و تنظیم کنید.','برنامه را روی Emulator اجرا کنید.','در مورد نقش Android SDK و Gradle در پروژه چند جمله یادداشت کنید.']]]},
{id:2,title:'مبانی کاتلین',desc:'زبان Kotlin را از مفاهیم پایه تا توابع، کلاس‌ها، مجموعه‌ها، حلقه‌ها، Null Safety و Lambda به شکل کاربردی یاد بگیرید.',topics:['متغیرها','انواع داده','شرط‌ها','توابع','کلاس‌ها','Objects','Data Class','List','MutableList','حلقه‌ها','Null Safety','Lambda'],sections:[
['Kotlin و ساختار یک برنامه',['Kotlin از ساختار ساده و خوانایی بالایی برخوردار است. کد معمولاً از متغیرها، توابع، کلاس‌ها و عبارت‌های کنترلی تشکیل می‌شود.','برای اجرای کدهای اندرویدی، همین مفاهیم پایه بعداً در Activityها، ViewModelها و Composableها استفاده می‌شوند.']],
['متغیرها و انواع داده',['برای مقدار قابل تغییر از var و برای مقدار غیرقابل‌تغییر از val استفاده کنید.','انواع متداول شامل Int، Long، Double، Float، Boolean، Char و String هستند.','بهتر است وقتی مقدار نباید تغییر کند از val استفاده شود تا کد قابل پیش‌بینی‌تر باشد.']],
['شرط‌ها',['if و else برای تصمیم‌گیری استفاده می‌شوند.','when برای بررسی چند حالت بسیار خوانا است و در پروژه‌های Kotlin کاربرد زیادی دارد.']],
['توابع و مقدار بازگشتی',['تابع با fun تعریف می‌شود. پارامترها نوع دارند و در صورت نیاز نوع مقدار بازگشتی بعد از ) نوشته می‌شود.','توابع کوچک و مشخص باعث می‌شوند کد قابل فهم‌تر و قابل استفاده مجدد باشد.']],
['کلاس‌ها و Objects',['کلاس یک الگو برای ساخت Objectها است و می‌تواند ویژگی و تابع داشته باشد.','Object برای ساخت یک نمونه singleton کاربرد دارد و در Kotlin مستقیماً با کلمه object تعریف می‌شود.']],
['Data Class',['Data Class برای نگهداری داده‌هایی مانند اطلاعات کاربر یا دانش‌آموز بسیار مناسب است.','Kotlin برای Data Class امکاناتی مانند toString، equals و copy را به‌صورت خودکار فراهم می‌کند.']],
['مجموعه‌ها: List و MutableList',['List یک مجموعه مرتب و معمولاً غیرقابل تغییر است.','MutableList مجموعه‌ای است که می‌توان به آن مقدار اضافه یا از آن مقدار حذف کرد.','می‌توانید با for روی عناصر مجموعه پیمایش انجام دهید.']],
['حلقه‌ها',['for برای پیمایش مجموعه یا محدوده استفاده می‌شود.','while تا زمانی که یک شرط برقرار باشد اجرا می‌شود.','از حلقه‌ها برای تکرار عملیات استفاده کنید و شرط پایان را به‌درستی مشخص کنید.']],
['Null Safety',['در Kotlin یک متغیر معمولی نمی‌تواند null باشد مگر اینکه نوع آن با علامت ? تعریف شود.','عملگر ?. برای دسترسی ایمن، ?: برای مقدار جایگزین و !! برای اعلام اطمینان کامل استفاده می‌شود؛ از !! با احتیاط استفاده کنید.']],
['Lambda expressions',['Lambda یک تابع کوتاه و بدون نام است که می‌توان آن را به متغیر داد یا به تابع دیگری ارسال کرد.','Lambdaها در کار با مجموعه‌ها، فیلتر کردن داده‌ها و بسیاری از APIهای Kotlin کاربرد دارند.']],
['نمونه‌های کد Kotlin',[]],
['تمرین‌ها',['یک متغیر val برای نام و یک var برای امتیاز تعریف کنید.','برنامه‌ای بنویسید که با if نمره را بررسی کند.','تابعی برای جمع دو عدد بنویسید و نتیجه را برگردانید.','کلاس Student با نام و سن ایجاد کنید.','یک Data Class به نام User بسازید.','یک List از چند نام بسازید و با حلقه چاپ کنید.','یک MutableList بسازید و یک نام به آن اضافه و سپس حذف کنید.','یک متغیر nullable تعریف کنید و با ?. مقدار آن را بررسی کنید.','با Lambda فقط اعداد بزرگ‌تر از ۱۰ را از یک List انتخاب کنید.']]]},
{id:3,title:'رابط کاربری مدرن با جت‌پک کامپوز',desc:'رابط کاربری اعلانی را یاد بگیرید و با Text، Button، Column، Row، Box، Modifier، Theme و Preview یک صفحه واقعی بسازید.',topics:['Declarative UI','Composable','Text','Button','Column','Row','Box','Modifier','dp','sp','Colors','Theme','Preview','State'],sections:[
['Jetpack Compose چیست؟',['Compose یک Toolkit مدرن برای ساخت UI اندروید است.','در مدل Declarative، شما مشخص می‌کنید UI در یک وضعیت خاص چگونه باشد و Compose هنگام تغییر وضعیت، بخش لازم رابط را دوباره محاسبه می‌کند.']],
['رابط سنتی در برابر رابط مدرن',['در سیستم View سنتی معمولاً با Viewها، Layoutها و XML کار می‌کنیم.','در Compose رابط کاربری با Kotlin و توابع Composable تعریف می‌شود و ساختار UI به شکل مستقیم‌تری در کد دیده می‌شود.','این رویکرد باعث می‌شود UI و منطق نمایش آن در بسیاری از موارد ساده‌تر و قابل ترکیب‌تر باشند.']],
['Composable Functions',['تابعی که با @Composable مشخص شود می‌تواند بخشی از رابط کاربری را تولید کند.','Composableها را می‌توان کوچک نگه داشت و از ترکیب چند Composable یک صفحه کامل ساخت.']],
['اجزای اصلی رابط کاربری',['Text برای نمایش متن است.','Button برای دریافت یک عمل از کاربر استفاده می‌شود.','Column عناصر را به صورت عمودی قرار می‌دهد.','Row عناصر را به صورت افقی قرار می‌دهد.','Box برای قرار دادن و هم‌پوشانی عناصر در یک محدوده کاربرد دارد.']],
['Modifier، dp و sp',['Modifier برای تنظیم اندازه، فاصله، پس‌زمینه، کلیک‌پذیری و بسیاری از ویژگی‌های UI استفاده می‌شود.','dp واحد رایج اندازه‌گیری ابعاد و فاصله‌ها در UI است.','sp برای اندازه متن مناسب است تا با تنظیمات دسترسی و اندازه فونت کاربر هماهنگ‌تر باشد.']],
['رنگ، Theme و طراحی',['Theme برای هماهنگ کردن رنگ‌ها، تایپوگرافی و شکل کلی برنامه استفاده می‌شود.','رنگ‌ها را باید با توجه به خوانایی، کنتراست و حالت روشن یا تاریک انتخاب کرد.','طراحی خوب فقط زیبا نیست؛ باید برای کاربر واضح، قابل پیش‌بینی و قابل استفاده باشد.']],
['Preview',['Preview امکان مشاهده یک Composable را در Android Studio بدون اجرای کامل برنامه فراهم می‌کند.','برای Preview بهتر است یک تابع جداگانه با @Preview تعریف کنید.']],
['نمونه تابع Composable',[]],
['نمونه Preview',[]],
['پروژه عملی: صفحه پروفایل',['یک صفحه پروفایل بسازید که شامل تصویر کاربر، نام، Student ID و دکمه Save باشد.','برای چیدمان اصلی از Column استفاده کنید.','اطلاعات کاربر را با Text نمایش دهید.','برای دکمه از Button استفاده کنید.','با Modifier فاصله و اندازه مناسب ایجاد کنید.','برای صفحه یک Preview بسازید و حالت‌های مختلف را بررسی کنید.']],
['نمونه ساخت صفحه پروفایل',[]],
['اصول طراحی رابط کاربری',['رابط کاربری را ساده نگه دارید.','عمل اصلی صفحه را واضح کنید.','از متن خوانا و اندازه مناسب استفاده کنید.','فاصله‌گذاری منظم داشته باشید.','کنتراست کافی بین متن و پس‌زمینه حفظ کنید.','رنگ‌ها و شکل اجزای رابط را هماهنگ نگه دارید.','روی صفحه عناصر غیرضروری زیادی قرار ندهید.','رابط را روی اندازه‌های مختلف صفحه آزمایش کنید.']],
['تمرین‌ها',['یک Composable با عنوان صفحه بسازید.','یک Button اضافه کنید و متن آن را تغییر دهید.','یک Column و Row برای چیدمان اطلاعات ایجاد کنید.','با Modifier padding و اندازه را تنظیم کنید.','رنگ و Theme صفحه را تغییر دهید.','برای صفحه یک Preview بسازید.','صفحه پروفایل پروژه را کامل کنید و آن را روی Emulator آزمایش کنید.']]]}
];
let completed=JSON.parse(localStorage.getItem('af-completed')||'[]');
const cards=document.getElementById('cards'),path=document.getElementById('pathList'),view=document.getElementById('lessonView'),content=document.getElementById('content');
const fa=n=>String(n).replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);
function update(){const n=completed.length;document.getElementById('percent').textContent=fa(Math.round(n/3*100))+'٪';document.getElementById('completed').textContent=fa(n)+' / ۳';document.getElementById('current').textContent=n<3?'درس '+fa(n+1):'دوره کامل شد';document.getElementById('progressBar').style.width=n/3*100+'%'}
function render(){const q=document.getElementById('search').value.trim().toLowerCase();const list=lessons.filter(l=>(l.title+' '+l.desc+' '+l.topics.join(' ')).toLowerCase().includes(q));cards.innerHTML=list.map(l=>`<div class="card"><span class="num">درس ${fa(l.id)}</span><h3>${l.title}</h3><p>${l.desc}</p><p class="topics"><b>موضوعات:</b> ${l.topics.join(' · ')}</p><p>${completed.includes(l.id)?'✓ تکمیل شده':'تکمیل نشده'}</p><a class="open" href="#lesson-${l.id}" onclick="openLesson(${l.id})">مشاهده درس ←</a></div>`).join('')||'<p>نتیجه‌ای برای جستجوی شما پیدا نشد.</p>';path.innerHTML=lessons.map(l=>`<a class="path-item" href="#lesson-${l.id}" onclick="openLesson(${l.id})"><strong>درس ${fa(l.id)}</strong><span>${l.title}</span><span>${completed.includes(l.id)?'✓':'←'}</span></a>`).join('');update()}
function sectionHTML(title,items){if(title==='نمونه کد Kotlin')return `<section><h2>نمونه‌های کد Kotlin</h2><p>در مثال‌های زیر چند مفهوم اصلی درس را در کنار هم می‌بینید:</p><pre>fun sum(a: Int, b: Int): Int {\n    return a + b\n}\n\nclass Student {\n    var name = ""\n    var age = 0\n}\n\ndata class User(\n    val name: String,\n    val age: Int\n)\n\nval names = listOf("Ali", "Sara", "Reza")\nval scores = mutableListOf(15, 18, 20)\n\nvar name: String? = null\nval length = name?.length ?: 0\n\nval numbers = listOf(5, 12, 20)\nval largeNumbers = numbers.filter { it > 10 }</pre></section>`;if(title==='نمونه‌های کد Kotlin')return '';if(title==='نمونه تابع Composable')return `<section><h2>نمونه تابع Composable</h2><p>این تابع یک متن را به عنوان بخشی از رابط کاربری تولید می‌کند.</p><pre>@Composable\nfun Greeting() {\n    Text(\n        text = "Hello Student"\n    )\n}</pre></section>`;if(title==='نمونه Preview')return `<section><h2>نمونه Preview</h2><p>با Preview می‌توان ظاهر Composable را هنگام توسعه بررسی کرد.</p><pre>@Preview(showBackground = true)\n@Composable\nfun PreviewGreeting() {\n    Greeting()\n}</pre></section>`;if(title==='نمونه ساخت صفحه پروفایل')return `<section><h2>نمونه ساخت صفحه پروفایل</h2><p>یک نمونه ساده برای شروع طراحی صفحه پروفایل:</p><pre>@Composable\nfun ProfileScreen() {\n    Column(\n        modifier = Modifier.padding(24.dp)\n    ) {\n        Text(text = "Student Profile")\n        Text(text = "Name: Ali")\n        Text(text = "Student ID: 1001")\n        Button(onClick = { /* Save */ }) {\n            Text("Save")\n        }\n    }\n}</pre></section>`;return `<section><h2>${title}</h2>${items.map(x=>title==='تمرین‌ها'?`<label class="exercise"><input type="checkbox">${x}</label>`:`<p>• ${x}</p>`).join('')}</section>`}
function openLesson(id){const l=lessons.find(x=>x.id===id);if(!l)return;document.getElementById('lessons').hidden=true;document.getElementById('path').hidden=true;view.hidden=false;content.className='lesson';content.innerHTML=`<span class="eyebrow">درس ${fa(l.id)}</span><h1>${l.title}</h1><p>${l.desc}</p>${l.sections.map(([title,items])=>sectionHTML(title,items)).join('')}<button class="btn primary complete" onclick="completeLesson(${id})">${completed.includes(id)?'✓ درس تکمیل شده است':'تکمیل درس'}</button>`;location.hash='lesson-'+id;window.scrollTo({top:0,behavior:'smooth'})}
function completeLesson(id){if(!completed.includes(id)){completed.push(id);localStorage.setItem('af-completed',JSON.stringify(completed))}render();openLesson(id)}
document.getElementById('search').addEventListener('input',render);document.getElementById('back').onclick=()=>{view.hidden=true;document.getElementById('lessons').hidden=false;document.getElementById('path').hidden=false;location.hash='lessons';window.scrollTo(0,0)};document.getElementById('menu').onclick=()=>document.getElementById('nav').classList.toggle('open');document.getElementById('theme').onclick=()=>document.body.classList.toggle('light');render();