const lessons=[
{id:1,title:'Introduction to Android and Compose',desc:'Understand Android, its tools, Kotlin, Compose, and your first project.',topics:['What is Android?','Android Studio','Android SDK','Android Emulator','Kotlin','Jetpack Compose','Project structure'],sections:[['Topics',['What is Android?','Methods of mobile application development','Android development tools','Android Studio','Android SDK','Android Emulator','Kotlin','Jetpack Compose','Android project structure','Creating the first Compose project']],['Lesson Summary',['The student should understand what Android is, how Android applications are developed, Android Studio, the Android SDK, Kotlin, Jetpack Compose, project structure, and how to create a basic Compose project.']],['Exercises',['Install Android Studio.','Create a new Kotlin Android project.','Create an Empty Activity using Jetpack Compose.','Change the default text.','Change the application name.','Change the application icon.']]]},
{id:2,title:'Kotlin Fundamentals',desc:'Learn the Kotlin building blocks needed for Android development.',topics:['Variables','Data types','Conditions','Functions','Classes','Data classes','Collections','Loops','Null Safety','Lambdas'],sections:[['Topics',['Kotlin basics','Variables','Data types','Conditions','Functions','Functions with return values','Classes','Objects','Data classes','Collections','Lists','MutableLists','Loops','Null Safety','Lambda expressions']],['Code Examples',['sum','student','user','nullable','names']],['Exercises',['Variables','Conditions','Functions','Classes','Data classes','Lists','Loops','Null Safety']]]},
{id:3,title:'Modern UI with Jetpack Compose',desc:'Build modern declarative interfaces using composable functions.',topics:['Composable Functions','Text','Button','Column','Row','Box','Modifier','dp','sp','Colors','Theme','Preview'],sections:[['Topics',['What is Jetpack Compose?','Traditional UI vs modern UI','Declarative UI','Composable Functions','Text','Button','Column','Row','Box','Modifier','dp','sp','Colors','Theme','Preview','Building a real UI']],['Composable Example',['compose']],['Preview Example',['preview']],['Practical Project',['Create a simple profile page containing a User image, User name, Student ID, and Save button.']],['UI Design Principles',['Keep the interface simple.','Make the main action clear.','Use readable text.','Use appropriate spacing.','Maintain good contrast.','Keep colors and design consistent.']]]}
];
let completed=JSON.parse(localStorage.getItem('af-completed')||'[]');
const cards=document.getElementById('cards'),path=document.getElementById('pathList'),view=document.getElementById('lessonView'),content=document.getElementById('content');
function update(){const n=completed.length;document.getElementById('percent').textContent=Math.round(n/3*100)+'%';document.getElementById('completed').textContent=n+' / 3';document.getElementById('current').textContent=n<3?'Lesson '+(n+1):'Complete';document.getElementById('progressBar').style.width=n/3*100+'%'}
function render(){const q=document.getElementById('search').value.toLowerCase();const list=lessons.filter(l=>(l.title+' '+l.desc+' '+l.topics.join(' ')).toLowerCase().includes(q));cards.innerHTML=list.map(l=>`<div class="card"><span class="num">LESSON ${l.id}</span><h3>${l.title}</h3><p>${l.desc}</p><p class="topics"><b>Topics:</b> ${l.topics.join(' · ')}</p><p>${completed.includes(l.id)?'✓ Completed':'Not completed'}</p><a class="open" href="#lesson-${l.id}" onclick="openLesson(${l.id})">Open lesson →</a></div>`).join('');path.innerHTML=lessons.map(l=>`<a class="path-item" href="#lesson-${l.id}" onclick="openLesson(${l.id})"><strong>Lesson ${l.id}</strong><span>${l.title}</span><span>${completed.includes(l.id)?'✓':'→'}</span></a>`).join('');update()}
function openLesson(id){const l=lessons.find(x=>x.id===id);if(!l)return;document.getElementById('lessons').hidden=true;document.getElementById('path').hidden=true;view.hidden=false;content.className='lesson';content.innerHTML=`<span class="eyebrow">LESSON ${l.id}</span><h1>${l.title}</h1><p>${l.desc}</p>${l.sections.map(([title,items])=>{if(title==='Code Examples')return `<section><h2>Code Examples</h2><pre>${`fun sum(a: Int, b: Int): Int {\n    return a + b\n}\n\nclass Student {\n    var name = ""\n    var age = 0\n}\n\ndata class User(\n    val name: String,\n    val age: Int\n)\n\nvar name: String? = null\n\nval names = listOf("Ali", "Sara", "Reza")`}</pre></section>`;if(title==='Composable Example')return `<section><h2>Composable Example</h2><pre>@Composable\nfun Greeting() {\n    Text(text = "Hello Student")\n}</pre></section>`;if(title==='Preview Example')return `<section><h2>Preview Example</h2><pre>@Preview(showBackground = true)\n@Composable\nfun PreviewGreeting() {\n    Greeting()\n}</pre></section>`;return `<section><h2>${title}</h2>${items.map(x=>title==='Exercises'?`<label class="exercise"><input type="checkbox">${x}</label>`:`<p>• ${x}</p>`).join('')}</section>`}).join('')}<button class="btn primary complete" onclick="completeLesson(${id})">${completed.includes(id)?'✓ Lesson completed':'Mark lesson complete'}</button>`;location.hash='lesson-'+id;window.scrollTo({top:0,behavior:'smooth'})}
function completeLesson(id){if(!completed.includes(id)){completed.push(id);localStorage.setItem('af-completed',JSON.stringify(completed))}render();openLesson(id)}
document.getElementById('search').addEventListener('input',render);document.getElementById('back').onclick=()=>{view.hidden=true;document.getElementById('lessons').hidden=false;document.getElementById('path').hidden=false;location.hash='lessons';window.scrollTo(0,0)};document.getElementById('menu').onclick=()=>document.getElementById('nav').classList.toggle('open');document.getElementById('theme').onclick=()=>document.body.classList.toggle('light');render();
