const lessons=[
{id:1,title:'مقدمه‌ای بر اندروید و کامپوز',desc:'با اندروید، ابزارهای توسعه، کاتلین، کامپوز و اولین پروژه خود آشنا شوید.',topics:['اندروید چیست؟','Android Studio','Android SDK','شبیه‌ساز اندروید','کاتلین','Jetpack Compose','ساختار پروژه'],sections:[['موضوعات',['اندروید چیست؟','روش‌های توسعه برنامه‌های موبایل','ابزارهای توسعه اندروید','Android Studio','Android SDK','Android Emulator','کاتلین','Jetpack Compose','ساختار پروژه اندروید','ساخت اولین پروژه Compose']],['خلاصه درس',['در پایان این درس باید بدانید اندروید چیست، برنامه‌های اندرویدی چگونه توسعه داده می‌شوند، Android Studio و Android SDK چه هستند، کاتلین و Jetpack Compose چه کاربردی دارند و ساختار یک پروژه اندرویدی چگونه است.']],['تمرین‌ها',['نصب Android Studio.','ساخت یک پروژه جدید اندرویدی با کاتلین.','ساخت یک Empty Activity با Jetpack Compose.','تغییر متن پیش‌فرض.','تغییر نام برنامه.','تغییر آیکون برنامه.']]]},
{id:2,title:'مبانی کاتلین',desc:'مفاهیم پایه کاتلین را که برای توسعه اندروید لازم دارید یاد بگیرید.',topics:['متغیرها','انواع داده','شرط‌ها','توابع','کلاس‌ها','Data Class','مجموعه‌ها','حلقه‌ها','Null Safety','Lambda'],sections:[['موضوعات',['مبانی کاتلین','متغیرها','انواع داده','شرط‌ها','توابع','توابع دارای مقدار بازگشتی','کلاس‌ها','اشیا','Data Class','مجموعه‌ها','List','MutableList','حلقه‌ها','Null Safety','عبارت‌های Lambda']],['نمونه کد',[]],['تمرین‌ها',['متغیرها','شرط‌ها','توابع','کلاس‌ها','Data Class','لیست‌ها','حلقه‌ها','Null Safety']]]},
{id:3,title:'رابط کاربری مدرن با Jetpack Compose',desc:'با استفاده از توابع کامپوز، رابط‌های کاربری مدرن و اعلانی بسازید.',topics:['توابع Composable','Text','Button','Column','Row','Box','Modifier','dp','sp','رنگ‌ها','Theme','Preview'],sections:[['موضوعات',['Jetpack Compose چیست؟','رابط کاربری سنتی در برابر رابط کاربری مدرن','رابط کاربری اعلانی','توابع Composable','Text','Button','Column','Row','Box','Modifier','dp','sp','رنگ‌ها','Theme','Preview','ساخت یک رابط کاربری واقعی']],['نمونه تابع Composable',[]],['نمونه Preview',[]],['پروژه عملی',['یک صفحه پروفایل ساده بسازید که شامل تصویر کاربر، نام کاربر، شناسه دانش‌آموزی و دکمه ذخیره باشد.']],['اصول طراحی رابط کاربری',['رابط کاربری را ساده نگه دارید.','عمل اصلی صفحه را واضح کنید.','از متن خوانا استفاده کنید.','فاصله‌گذاری مناسب داشته باشید.','کنتراست مناسب را حفظ کنید.','رنگ‌ها و طراحی را هماهنگ نگه دارید.']]]}
];
let completed=JSON.parse(localStorage.getItem('af-completed')||'[]');
const cards=document.getElementById('cards'),path=document.getElementById('pathList'),view=document.getElementById('lessonView'),content=document.getElementById('content');
const fa=n=>String(n).replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);
function update(){const n=completed.length;document.getElementById('percent').textContent=fa(Math.round(n/3*100))+'٪';document.getElementById('completed').textContent=fa(n)+' / ۳';document.getElementById('current').textContent=n<3?'درس '+fa(n+1):'تکمیل شد';document.getElementById('progressBar').style.width=n/3*100+'%'}
function render(){const q=document.getElementById('search').value.trim().toLowerCase();const list=lessons.filter(l=>(l.title+' '+l.desc+' '+l.topics.join(' ')).toLowerCase().includes(q));cards.innerHTML=list.map(l=>`<div class="card"><span class="num">درس ${fa(l.id)}</span><h3>${l.title}</h3><p>${l.desc}</p><p class="topics"><b>موضوعات:</b> ${l.topics.join(' · ')}</p><p>${completed.includes(l.id)?'✓ تکمیل شده':'تکمیل نشده'}</p><a class="open" href="#lesson-${l.id}" onclick="openLesson(${l.id})">مشاهده درس ←</a></div>`).join('')||'<p>نتیجه‌ای برای جستجوی شما پیدا نشد.</p>';path.innerHTML=lessons.map(l=>`<a class="path-item" href="#lesson-${l.id}" onclick="openLesson(${l.id})"><strong>درس ${fa(l.id)}</strong><span>${l.title}</span><span>${completed.includes(l.id)?'✓':'←'}</span></a>`).join('');update()}
function openLesson(id){const l=lessons.find(x=>x.id===id);if(!l)return;document.getElementById('lessons').hidden=true;document.getElementById('path').hidden=true;view.hidden=false;content.className='lesson';content.innerHTML=`<span class="eyebrow">درس ${fa(l.id)}</span><h1>${l.title}</h1><p>${l.desc}</p>${l.sections.map(([title,items])=>{if(title==='نمونه کد')return `<section><h2>نمونه کد</h2><pre>fun sum(a: Int, b: Int): Int {\n    return a + b\n}\n\nclass Student {\n    var name = ""\n    var age = 0\n}\n\ndata class User(\n    val name: String,\n    val age: Int\n)\n\nvar name: String? = null\n\nval names = listOf("Ali", "Sara", "Reza")</pre></section>`;if(title==='نمونه تابع Composable')return `<section><h2>نمونه تابع Composable</h2><pre>@Composable\nfun Greeting() {\n    Text(text = "Hello Student")\n}</pre></section>`;if(title==='نمونه Preview')return `<section><h2>نمونه Preview</h2><pre>@Preview(showBackground = true)\n@Composable\nfun PreviewGreeting() {\n    Greeting()\n}</pre></section>`;return `<section><h2>${title}</h2>${items.map(x=>title==='تمرین‌ها'?`<label class="exercise"><input type="checkbox">${x}</label>`:`<p>• ${x}</p>`).join('')}</section>`}).join('')}<button class="btn primary complete" onclick="completeLesson(${id})">${completed.includes(id)?'✓ درس تکمیل شده است':'تکمیل درس'}</button>`;location.hash='lesson-'+id;window.scrollTo({top:0,behavior:'smooth'})}
function completeLesson(id){if(!completed.includes(id)){completed.push(id);localStorage.setItem('af-completed',JSON.stringify(completed))}render();openLesson(id)}
document.getElementById('search').addEventListener('input',render);document.getElementById('back').onclick=()=>{view.hidden=true;document.getElementById('lessons').hidden=false;document.getElementById('path').hidden=false;location.hash='lessons';window.scrollTo(0,0)};document.getElementById('menu').onclick=()=>document.getElementById('nav').classList.toggle('open');document.getElementById('theme').onclick=()=>document.body.classList.toggle('light');render();
